version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    reviewers:
      - 'Sigurs'
    assignees:
      - 'Sigurs'
    groups:
      npm-dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
